# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "github_private_repository_release_download_strategy"
class Dsctl < Formula
  desc ""
  homepage ""
  version "0.5.1"

  depends_on "kubectl"

  on_macos do
    on_intel do
      url "https://github.com/digitalservicebund/dsctl/releases/download/v0.5.1/dsctl_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "66253966c3e60b556703d89dc67912d771f79dd98e8999f3dc2bc15bc317119f"

      def install
        bin.install "dsctl"
        bash_completion.install "completions/dsctl.bash" => "dsctl"
        fish_completion.install "completions/dsctl.fish"
        zsh_completion.install "completions/dsctl.zsh" => "_dsctl"
      end
    end
    on_arm do
      url "https://github.com/digitalservicebund/dsctl/releases/download/v0.5.1/dsctl_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "df60c4d9e27bd34bfd6e9024c2f02353b7a64add02511d618abb6416c178dddd"

      def install
        bin.install "dsctl"
        bash_completion.install "completions/dsctl.bash" => "dsctl"
        fish_completion.install "completions/dsctl.fish"
        zsh_completion.install "completions/dsctl.zsh" => "_dsctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/digitalservicebund/dsctl/releases/download/v0.5.1/dsctl_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "5b91f10f4284398d01fb25fe9edcb53ad6ff3e544ac6c115cb564db1d757606f"

        def install
          bin.install "dsctl"
          bash_completion.install "completions/dsctl.bash" => "dsctl"
          fish_completion.install "completions/dsctl.fish"
          zsh_completion.install "completions/dsctl.zsh" => "_dsctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/digitalservicebund/dsctl/releases/download/v0.5.1/dsctl_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "3f9f9d2b0a783b86191da8222771178306ad5776f63be6b1fff0d025309fd668"

        def install
          bin.install "dsctl"
          bash_completion.install "completions/dsctl.bash" => "dsctl"
          fish_completion.install "completions/dsctl.fish"
          zsh_completion.install "completions/dsctl.zsh" => "_dsctl"
        end
      end
    end
  end
end
