# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "github_private_repository_release_download_strategy"
class Dsctl < Formula
  desc ""
  homepage ""
  version "0.4.5"

  depends_on "kubectl"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/digitalservicebund/dsctl/releases/download/v0.4.5/dsctl_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "cf7c761b83bca680a50579ec6def126df855a3e70a7971404a661c3e55f94ed3"

      def install
        bin.install "dsctl"
        bash_completion.install "completions/dsctl.bash" => "dsctl"
        fish_completion.install "completions/dsctl.fish"
        zsh_completion.install "completions/dsctl.zsh" => "_dsctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/digitalservicebund/dsctl/releases/download/v0.4.5/dsctl_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "43cf1004b4598218967b7490e2fb5c748b5931312e82d9e927b95f9a7327275f"

      def install
        bin.install "dsctl"
        bash_completion.install "completions/dsctl.bash" => "dsctl"
        fish_completion.install "completions/dsctl.fish"
        zsh_completion.install "completions/dsctl.zsh" => "_dsctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/digitalservicebund/dsctl/releases/download/v0.4.5/dsctl_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "227d892a2f91e75edb0a6aa64975a384b1afc52fb568ff1393b6a431595a2665"

      def install
        bin.install "dsctl"
        bash_completion.install "completions/dsctl.bash" => "dsctl"
        fish_completion.install "completions/dsctl.fish"
        zsh_completion.install "completions/dsctl.zsh" => "_dsctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/digitalservicebund/dsctl/releases/download/v0.4.5/dsctl_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "a7f6a6d606190e0a5d4c79b866b11e661547a90f89815b37d3900dbe1848b411"

      def install
        bin.install "dsctl"
        bash_completion.install "completions/dsctl.bash" => "dsctl"
        fish_completion.install "completions/dsctl.fish"
        zsh_completion.install "completions/dsctl.zsh" => "_dsctl"
      end
    end
  end
end
