# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "github_private_repository_release_download_strategy"
class Dsctl < Formula
  desc ""
  homepage ""
  version "0.6.1"

  depends_on "kubectl"

  on_macos do
    on_intel do
      url "https://github.com/digitalservicebund/dsctl/releases/download/v0.6.1/dsctl_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8e81805e3335b43b50c8a284e75a72ab2b48eef444ffd19d40226a41603dbe77"

      def install
        bin.install "dsctl"
        bash_completion.install "completions/dsctl.bash" => "dsctl"
        fish_completion.install "completions/dsctl.fish"
        zsh_completion.install "completions/dsctl.zsh" => "_dsctl"
      end
    end
    on_arm do
      url "https://github.com/digitalservicebund/dsctl/releases/download/v0.6.1/dsctl_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "4817780f77c719e475f6fc19e895a5ca0fd9c23af95904ab8e2a5ef3455abfa3"

      def install
        bin.install "dsctl"
        bash_completion.install "completions/dsctl.bash" => "dsctl"
        fish_completion.install "completions/dsctl.fish"
        zsh_completion.install "completions/dsctl.zsh" => "_dsctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/digitalservicebund/dsctl/releases/download/v0.6.1/dsctl_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "67d44dadb66636d711a9da52fc4aedc9cc917e0e38e921ed2fcc1e3be363f687"

        def install
          bin.install "dsctl"
          bash_completion.install "completions/dsctl.bash" => "dsctl"
          fish_completion.install "completions/dsctl.fish"
          zsh_completion.install "completions/dsctl.zsh" => "_dsctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/digitalservicebund/dsctl/releases/download/v0.6.1/dsctl_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "37728de8eac00ab727eb8652cb13d764b655d6d5ae20e73a54d9d39166fc0340"

        def install
          bin.install "dsctl"
          bash_completion.install "completions/dsctl.bash" => "dsctl"
          fish_completion.install "completions/dsctl.fish"
          zsh_completion.install "completions/dsctl.zsh" => "_dsctl"
        end
      end
    end
  end
end
